### ISSUE TITLE
Fehler 401 bei Terminsuche

### ISSUE THREAD

**Issue by iamnotturner** [iamnotturner/vaccipy#208]
Als Laie ist es sooo schwierig, hier überhaupt durchzublicken. Deshalb schreibe ich wieder hier, weil ich nichts Passenderes finde. Dieses, was bei euch "Release" heißt und für mich "Update" bedeutet, hat zumindest geholfen, Codes zu generieren. Mit den Codes kann ich aber leider keine Terminpaare buchen (Fehler 401). Wenn ich nachlese, was der Fehler 401 bedeutet - und zwar, dass Impfzentrum und Code nicht zusammenpassen - dann hat mich das Release doch nicht weitergebracht, denn die Codes funktionieren ja nicht für mein Impfzentrum :-(

Verschiebt den Kommentar gern dorthin, wo er nach eurem Wissen hingehört. Die Themen überschneiden sich ja

_Originally posted by @Sylwuscha in https://github.com/iamnotturner/vaccipy/issues/191#issuecomment-850406526_

**Comment by iamnotturner** [comment]
@Sylwuscha

dass Release "Update" bedeutet ist richtig und mehr musst du dazu auch nicht wissen :-) 
Wenns ein neues "Update" gibt reicht es, wenn du einfach die Datei downloadest.

Zu deinem Problem: hast du mal versucht mit deinem Code online beim [Impfterminservice](https://www.impfterminservice.de/impftermine) einen Termin manuell zu suchen? Du wirst feststellen, dass der Code nicht für das gewählte Impfzentrum geht. Und genau das sagt die Fehlermeldung 401 aus. Also brauchst du entweder einen anderen Code für das Impfzentrum, oder du musst eine andere PLZ wählen :-) 

Bevor du das Programm startest kannst du online nochmal manuell prüfen, ob du mit dem Code bei deinen Impfzentren nach Terminen suchen kannst.

**Comment by Sylwuscha** [comment]
Nun bin ich total verwirrt.Also nach dem Update konnte ich für Aalen nach Codes suchen.Im Anschluss wollte ich auch die Automatik zur Terminesuche laufen lassen.Aber es kommt Fehler 401, dass der Code nicht für Aalen passt.Jetzt hieß es, ich soll den Code manuell einsetzen, um zu sehen, dass der Code für Aalen nicht passt. Aber: Er scheint zu passen, denn es erscheint keine Fehlermeldung! Heißt dass, er ist auf jeden Fall gültig?Aber warum klappt dann die automatische Suche nicht?-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.05.21, 16:05, Tim Reibe ***@***.***> schrieb:


@Sylwuscha

dass Release "Update" bedeutet ist richtig und mehr musst du dazu auch nicht wissen :-)

Wenns ein neues "Update" gibt reicht es, wenn du einfach die Datei downloadest.

Zu deinem Problem: hast du mal versucht mit deinem Code online beim Impfterminservice einen Termin manuell zu suchen? Du wirst feststellen, dass der Code nicht für das gewählte Impfzentrum geht. Und genau das sagt die Fehlermeldung 401 aus. Also brauchst du entweder einen anderen Code für das Impfzentrum, oder du musst eine andere PLZ wählen :-)

Bevor du das Programm startest kannst du online nochmal manuell prüfen, ob du mit dem Code bei deinen Impfzentren nach Terminen suchen kannst.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/iamnotturner/vaccipy/issues/208#issuecomment-850443463",

"url": "https://github.com/iamnotturner/vaccipy/issues/208#issuecomment-850443463",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by iamnotturner** [comment]
Also wenn du den Code auf der Website eingibst für das Impfzentrum mit der PLZ 73430 gelangst du ganz normal zur Terminsuche?

**Comment by Sylwuscha** [comment]
Ja, und jetzt hat es sogar mit der automatischen Suche geklappt. Jetzt bin ich happy der Familie helfen zu können -- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.05.21, 18:05, Tim Reibe ***@***.***> schrieb:


Also wenn du den Code auf der Website eingibst für das Impfzentrum mit der PLZ 73430 gelangst du ganz normal zur Terminsuche?



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/iamnotturner/vaccipy/issues/208#issuecomment-850520507",

"url": "https://github.com/iamnotturner/vaccipy/issues/208#issuecomment-850520507",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by iamnotturner** [comment]
Ich drücke dir/euch die Daumen!
