### ISSUE TITLE
[Feature Request] Allow the user to cancel an appointment booking after showing time, date and place of booking

### ISSUE THREAD

**Issue by marvinruder** [iamnotturner/vaccipy#232]
When an available appointment has been found, www.impfterminservice.de usually reserves the appointment for 10 minutes (at least using the webpage, I do not know if their API, if existent, offers a similar service – this would be important to know). After the script found the appointment, it appears to print a BELL character to alert the user that an appointment became available, then immediately books the appointment. However, since it is not possible at the moment to consider times and days where the user cannot attend the appointment, it would be helpful (and may be easier to implement) to have a short time period (e.g. 30 seconds) where the user can manually check whether he is able to attend the proposed appointment and, if not, can cancel the booking process at the press of a button. Therefore, the amount of misbookings can be minimized. After a booking has been canceled, it may be advisable to pause the script for a few moments to wait for the appointment being taken by another person so the appointment will not be reserved and released by our script multiple times.

**Comment by andoorius** [comment]
I had quite a bit trouble with "reserved for 10min". This does not really work! If you are to slow (<<10min) - I guess it took me <<2min it happens quite often (about 1 out of 10 bookings) that this appointment was taken by some else. 
So I'm not sure about this feature. If it is implemented the waiting-time should be flexible. I will always stick with "0" :-)
For me the given options from Beta 1.0.5. on is perfekt!

**Comment by Floskinner** [comment]
The idea is good!

I had the same experience as andoorius. I found an appointment, but didn't know exactly what the address was. So I entered all the data 5 minutes later and wanted to book the appointment -> appointment no longer available...

@marvinruder 
> However, since it is not possible at the moment to consider times and days where the user cannot attend the appointment[...]

Maybe to get around your problem with unavailable dates, you could use the Beta v1.0.6 GUI. Here you can exclude certain days up to 1 week in advance:
![vaccipy - Zeitspanne](https://user-images.githubusercontent.com/58706771/120121930-55042900-c1a6-11eb-982f-88ef93c8d201.png)

**Comment by iamnotturner** [comment]
As @andoorius already mentioned the reservation time is not really reliable.
@Floskinner offers a nice feature in its GUI that we're implementing in the non-GUI version aswell in the near future. Setting day and time range has to be sufficient. We don't want the user to interact with the script after starting the appointment search. 

Misbookings may happen, but this shouldn't be an issue since people can (and I hope they do) easily cancel their appointment online at "Buchung verwalten". Once it is cancelled the appointment is thrown back into the queue and will be offered to the next one (just after a few minutes, no needs to worry at all).
